- type: job
  id: BlueShieldEnsign
  name: job-name-blueshield-ensign
  description: job-description-blueshield-ensign
  playTimeTracker: JobBlueShieldEnsign
  requirements:
    - !type:DepartmentTimeRequirement
      department: BlueShield
      time: 62000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 62000 # 20 hrs
    - !type:AgeRequirement
      requiredAge: 35
  startingGear: BlueShieldEnsignGear
  icon: JobIconBlueShield
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
    # Fish-End
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldEnsignGear
  equipment:
    shoes: ClothingShoesBootsBlueShieldFilled
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterArmorBlueShield
    id: BlueShieldEnsignPDA
    ears: ClothingHeadsetBlueShieldEnsign
    belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat
    pocket2: WeaponTaser # fish-add
  storage:
    back:
    - HandheldBSOCrewMonitor

- type: chameleonOutfit
  id: BlueShieldEnsignChameleonOutfit
  job: BlueShieldEnsign
  icon: JobIconBlueShield
  equipment:
    shoes: ClothingShoesBootsBlueShieldFilled
    eyes: ClothingEyesGlassesBlueShield
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterArmorBlueShield
    belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat