using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider, min: 0.2f); // Fish-Edit
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        // FIsh edit - CRT accessibility preferences
        var crtTheme = Control.AddOptionCheckBox(FishCVars.FishCrtThemeEnabled, FishCrtThemeEnabledCheckBox);
        Control.AddOptionCheckBox(FishCVars.FishCrtEffectsEnabled, FishCrtEffectsEnabledCheckBox);
        crtTheme.ImmediateValueChanged += _ => UpdateCrtEffectsDisabled();
        Control.ValuesReset += UpdateCrtEffectsDisabled;
        // FIsh edit end

        Control.Initialize();
        UpdateCrtEffectsDisabled();
    }

    // FIsh edit
    private void UpdateCrtEffectsDisabled()
    {
        FishCrtEffectsEnabledCheckBox.Disabled = !FishCrtThemeEnabledCheckBox.Pressed;
    }
    // FIsh edit end
}
