- type: jobIcon
  parent: JobIcon
  id: IconCoreBase
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: CoreBase
  jobName: Республиканцы
  isShaded: true
  offset: 0
  priority: 1


- type: jobIcon
  parent: IconCoreBase
  id: IconCorePC0I5
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: CorePC0I5


- type: jobIcon
  parent: IconCoreBase
  id: IconCorePM1
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: CorePM1


- type: jobIcon
  parent: IconCoreBase
  id: IconCorePE1
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: CorePE1


- type: jobIcon
  parent: IconCoreBase
  id: IconCoreAi
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: CoreAi
