- type: job
  id: JobCoreBase
  name: job-name-corebase
  description: job-description-corebase
  playTimeTracker: OverAllCoreBase
  setPreference: true
  weight: 2
  jobEntity: MobHumanCoreP0WMF5
  icon: "IconCoreBase"
  canBeAntag: false
  access:
  - AssCoreBase
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant


- type: job
  id: JobCorePC0I5
  name: job-name-corepc0i5
  description: job-description-corepc0i5
  playTimeTracker: OverAllCorePC0I5
  setPreference: true
  weight: 5
  jobEntity: MobHumanCorePC0I5WMF5
  icon: "IconCorePC0I5"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePC0I5
  - AssCorePM1
  - AssCorePE1
  alwaysUseSpawner: true
  supervisors: job-supervisors-republic-council


- type: job
  id: JobCorePM1
  name: job-name-corepm1
  description: job-description-corepm1
  playTimeTracker: OverAllCorePM1
  setPreference: true
  weight: 3
  jobEntity: MobHumanCorePM1WMF5
  icon: "IconCorePM1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePM1
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant


- type: job
  id: JobCorePE1
  name: job-name-corepe1
  description: job-description-corepe1
  playTimeTracker: OverAllCorePE1
  setPreference: true
  weight: 4
  jobEntity: MobHumanCorePE1WMF5
  icon: "IconCorePE1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePE1
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant
