using System;
using System.Globalization;
using Content.Shared.Atmos.Piping.Trinary.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Fish.Atmos.FIlter;

[GenerateTypedNameReferences]
public sealed partial class GasRangeTemperatureFilterWindow : DefaultWindow
{
    private const float MinTemperature = 2.7f;
    private const float MaxTemperature = 100000f;
    private const float MaxTransferRate = 1000f;

    public bool FilterStatus = true;
    public float LowTemperature = MinTemperature;
    public float HighTemperature = 1000f;
    public float TransferRate = 1000f;

    public event Action? ToggleStatusPressed;
    public event Action<float>? TransferRateSet;
    public event Action<float, float>? RangeChanged;

    public GasRangeTemperatureFilterWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleStatusButton.OnPressed += _ =>
        {
            FilterStatus = !FilterStatus;
            ToggleStatusButton.Text = FilterStatus
                ? Loc.GetString("comp-gas-range-temp-filter-ui-status-enabled")
                : Loc.GetString("comp-gas-range-temp-filter-ui-status-disabled");
            ToggleStatusPressed?.Invoke();
        };

        TransferRateInput.OnTextChanged += _ => ValidateTransferRateButton();
        SetRateButton.OnPressed += _ =>
        {
            if (float.TryParse(TransferRateInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out float rate))
            {
                rate = Math.Clamp(rate, 0f, MaxTransferRate);
                if (Math.Abs(rate - TransferRate) > 0.001f)
                {
                    TransferRateSet?.Invoke(rate);
                }
                TransferRateInput.Text = rate.ToString("F0", CultureInfo.CurrentCulture);
                SetRateButton.Disabled = true;
            }
            else
            {
                TransferRateInput.Text = TransferRate.ToString("F0", CultureInfo.CurrentCulture);
                SetRateButton.Disabled = true;
            }
        };

        SetRangeButton.OnPressed += _ =>
        {
            if (float.TryParse(LowTempInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out float low) &&
                float.TryParse(HighTempInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out float high))
            {
                low = Math.Clamp(low, MinTemperature, MaxTemperature);
                high = Math.Clamp(high, MinTemperature, MaxTemperature);

                if (Math.Abs(low - LowTemperature) > 0.001f || Math.Abs(high - HighTemperature) > 0.001f)
                {
                    RangeChanged?.Invoke(low, high);
                }

                LowTempInput.Text = FormatFloat(low);
                HighTempInput.Text = FormatFloat(high);
                SetRangeButton.Disabled = true;
            }
            else
            {
                LowTempInput.Text = FormatFloat(LowTemperature);
                HighTempInput.Text = FormatFloat(HighTemperature);
                SetRangeButton.Disabled = true;
            }
        };

        LowTempInput.OnTextChanged += _ => ValidateRangeButton();
        HighTempInput.OnTextChanged += _ => ValidateRangeButton();
    }

    private string FormatFloat(float value) => value.ToString("F1", CultureInfo.CurrentCulture);

    private void ValidateTransferRateButton()
    {
        SetRateButton.Disabled = !float.TryParse(TransferRateInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out _);
    }

    private void ValidateRangeButton()
    {
        SetRangeButton.Disabled = !(float.TryParse(LowTempInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out _) &&
                                    float.TryParse(HighTempInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out _));
    }

    public void SetState(GasRangeTemperatureFilterBoundUserInterfaceState state)
    {
        Title = state.FilterLabel;
        FilterStatus = state.Enabled;
        ToggleStatusButton.Text = state.Enabled
            ? Loc.GetString("comp-gas-range-temp-filter-ui-status-enabled")
            : Loc.GetString("comp-gas-range-temp-filter-ui-status-disabled");

        TransferRate = state.TransferRate;
        TransferRateInput.Text = state.TransferRate.ToString("F0", CultureInfo.CurrentCulture);
        SetRateButton.Disabled = true;

        LowTemperature = state.LowTemperature;
        HighTemperature = state.HighTemperature;
        LowTempInput.Text = FormatFloat(state.LowTemperature);
        HighTempInput.Text = FormatFloat(state.HighTemperature);
        SetRangeButton.Disabled = true;

        UpdateStatusLabel();
    }

    private void UpdateStatusLabel()
    {
        CurrentStatusLabel.Text = Loc.GetString("comp-gas-range-temp-filter-ui-status-text",
            ("enabled", FilterStatus ? Loc.GetString("comp-gas-range-temp-filter-ui-status-enabled") : Loc.GetString("comp-gas-range-temp-filter-ui-status-disabled")),
            ("low", FormatFloat(LowTemperature)),
            ("high", FormatFloat(HighTemperature)),
            ("rate", TransferRate.ToString("F0", CultureInfo.CurrentCulture)));
    }
}