
##CBURNLeader

- type: job
  id: CBURNLeader
  name: job-name-cburnleader
  description: job-description-cburnleader
  playTimeTracker: JobCBURNLeader
  setPreference: false
  startingGear: CBURNGearLeader
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CBURNGearLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitCBURNLeader
    id: CBURNPDA
    shoes: ClothingShoesBootsCombatFilled
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
  storage:
    back:
      - WeaponShotgunSPAS12
      - BoxShotgunIncendiary
      - GrenadeFlashBang
      - PillAmbuzolPlus
      - PillAmbuzol
      - ClothingHandsPowerGlovesUplinkNTERTCBURNLeader

- type: chameleonOutfit
  id: CBURNLeaderChameleonOutfit
  job: CBURNLeader
  hasMindShield: true
  equipment:
    outerClothing: ClothingOuterHardsuitCBURNLeader
    neck: ClothingNeckScarfStripedBrown
