- type: startingGear
  id: DeathSquadGearFish
  parent: DeathSquadGear
  equipment:
    mask: ClothingMaskGasDeathSquadFish
    outerClothing: ClothingOuterHardsuitDeathsquadFish
    shoes: ClothingShoesBootsMagDeathSquadFish
    gloves: ClothingHandsGlovesDeathSquadFish
    eyes: ClothingEyesHudMedSec
    back: ClothingDeathSquadronBackpackFish
  inhand: []

- type: startingGear
  id: DeathSquadGearFishBudget
  parent: DeathSquadGearFish
  equipment:
    gloves: ClothingHandsPowerGlovesUplinkNTERTDeathSquadFish


