using Content.Client.UserInterface.Controls;
using Content.Shared._Fish.ObrCall;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Fish.ObrCall;

[GenerateTypedNameReferences]
public sealed partial class ObrCallWindow : FancyWindow
{
    public event Action<string, string>? OnCallPressed;

    public ObrCallWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ObrCallBoundUserInterfaceState state)
    {
        HeaderLabel.Text = state.IsPurchaseMode
            ? Loc.GetString("obr-call-window-header-station")
            : Loc.GetString("obr-call-window-header-centcomm");

        BalanceBox.Visible = state.IsPurchaseMode;
        BalanceLabel.Text = Loc.GetString("obr-call-window-balance-value", ("amount", state.StationBalance));

        if (!string.IsNullOrWhiteSpace(state.StatusMessage))
        {
            StatusLabel.Visible = true;
            StatusLabel.Text = state.StatusMessage;
        }
        else
        {
            StatusLabel.Visible = false;
        }

        TeamsContainer.DisposeAllChildren();

        foreach (var team in state.Teams)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 2,
            };

            row.AddChild(new Label
            {
                Text = team.Name,
                StyleClasses = { "LabelKeyText" },
            });

            if (!string.IsNullOrWhiteSpace(team.Description))
            {
                row.AddChild(new Label
                {
                    Text = team.Description,
                });
            }

            if (team.Cost is { } cost)
            {
                row.AddChild(new Label
                {
                    Text = Loc.GetString("obr-call-window-cost", ("amount", cost)),
                });
            }

            if (!string.IsNullOrWhiteSpace(team.UnavailableReason))
            {
                row.AddChild(new Label
                {
                    Text = team.UnavailableReason,
                    FontColorOverride = Color.OrangeRed,
                });
            }

            var teamId = team.PrototypeId;
            var button = new Button
            {
                Text = Loc.GetString("obr-call-window-call-button"),
                Disabled = !team.Available,
                HorizontalExpand = true,
                MinHeight = 36,
            };

            button.OnPressed += _ =>
            {
                var mission = Rope.Collapse(MissionInput.TextRope);
                OnCallPressed?.Invoke(teamId, mission);
            };

            row.AddChild(button);
            TeamsContainer.AddChild(row);
            TeamsContainer.AddChild(new Control { MinHeight = 4 });
        }
    }
}
