- type: job
  id: CentCommOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentCommOfficial
  requirements:
  - !type:DiscordRoleRequirement
  weight: 30
  setPreference: false
  startingGear: CentCommOfficialGear
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentCommOfficialGear
  equipment:
    # jumpsuit: ClothingUniformJumpsuitCentcomOfficial # Fish-edit
    # shoes: ClothingShoesColorBlack # Fish-edit
    # gloves: ClothingHandsGlovesColorWhite # Fish-edit
    # neck: ClothingNeckCloakCentcom # Fish-edit
    # head: ClothingHeadHatCentcom # Fish-edit
    # eyes: ClothingEyesGlassesSunglasses # Fish-edit
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    # belt: WeaponPistolN1984 # Fish-edit
  storage:
    back:
    - PenCentcom
    - BoxFolderBlack

- type: chameleonOutfit
  id: CentCommOfficialChameleonOutfit
  job: CentCommOfficial
  equipment:
    neck: ClothingNeckCloakCentcom
