- type: job
  id: NanoTrasenRepresentative
  name: job-name-ntrep
  description: job-description-ntrep
  playTimeTracker: JobNanoTrasenRepresentative
  requirements:
    - !type:DiscordRoleRequirement #Fish-edit
  startingGear: NanoTrasenRepresentativeGear
  icon: JobIconNanotrasen_representative #Fish-edit
  joinNotifyCrew: true
  radioBold: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups: # Fish-edit
  - AllAccess
  alternativeTitles:
  - job-alt-title-nt-diplomat
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantBlueShield ]
    - !type:AddComponentSpecial
      components:
      - type: CommandStaff

- type: startingGear
  id: NanoTrasenRepresentativeGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesSunGlassesHudSkill
    head: ClothingHeadHatCapNtrep
    id: NanoTrasenRepresentativePDA
    ears: ClothingHeadsetAltRepresentativeNT
    pocket1: FlippoEngravedLighter
    pocket2: PenCentcom
  storage:
    back:
    - RubberStampNtrep
    - CaneNT
    - RubberStampVeto #sunrise-edit

- type: chameleonOutfit
  id: NanoTrasenRepresentativeChameleonOutfit
  job: NanoTrasenRepresentative
