- type: gameMapPool
  id: FishMapPool
  maps:
# High-pop
  - FishDelta
  - FishIrefit
  - FishBox
  - FishSuharik
# Mid-pop
  - FishMarathon
  - FishOasis
  - FishPlasma
  - FishBagel
# Low-pop
  - FishCase
  - FishSnowball
  - FishPacked
  - FishTerraBiome

