- type: factionIcon
  id: FactionIconArmBase
  hideInContainer: false
  isShaded: false
  hideOnStealth: false
  offset: 0
  locationPreference: Right
  priority: 0
  showTo:
    components:
      - Spectral
      - Thruster
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmBase


- type: factionIcon
  id: FactionIconArmPC0I5
  hideInContainer: false
  isShaded: false
  hideOnStealth: false
  offset: 0
  locationPreference: Right
  priority: 0
  showTo:
    components:
      - Spectral
      - Thruster
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPC0I5


- type: factionIcon
  id: FactionIconArmPM1
  hideInContainer: false
  isShaded: false
  hideOnStealth: false
  offset: 0
  locationPreference: Right
  priority: 0
  showTo:
    components:
      - Spectral
      - Thruster
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPM1


- type: factionIcon
  id: FactionIconArmPE1
  hideInContainer: false
  isShaded: false
  hideOnStealth: false
  offset: 0
  locationPreference: Right
  priority: 0
  showTo:
    components:
      - Spectral
      - Thruster
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPE1


- type: factionIcon
  id: FactionIconArmAi
  hideInContainer: false
  isShaded: false
  hideOnStealth: false
  offset: 0
  locationPreference: Right
  priority: 0
  showTo:
    components:
      - Spectral
      - Thruster
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmAi


#TimeTrecker
