- type: jobIcon
  parent: JobIcon
  id: IconArmBase
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmBase
  jobName: Повстанцы
  isShaded: true
  offset: 0
  priority: 1


- type: jobIcon
  parent: IconArmBase
  id: IconArmPC0I5
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPC0I5


- type: jobIcon
  parent: IconArmBase
  id: IconArmPM1
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPM1


- type: jobIcon
  parent: IconArmBase
  id: IconArmPE1
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPE1


- type: jobIcon
  parent: IconArmBase
  id: IconArmAi
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmAi
