using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Fish.RoundEnd
{
    [GenerateTypedNameReferences]
    public sealed partial class NoEorgPopup : FancyWindow
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IUriOpener _uri = default!;

        private float _remainingTime;

        public NoEorgPopup()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            _cfg.OnValueChanged(FishCVars.EorgPopupTime, duration => _remainingTime = duration, true);

            InitializeUI();
            InitializeEvents();
        }

        private void InitializeUI()
        {
            TitleLabel.Text = Loc.GetString("no-eorg-popup-label");

            var msg = _cfg.GetCVar(FishCVars.EorgPopupMessage);
            if (string.IsNullOrWhiteSpace(msg))
                msg = Loc.GetString("no-eorg-popup-message");
            MessageLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(msg));

            RuleLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("no-eorg-popup-rule")));

            DiscordButton.Text = Loc.GetString("no-eorg-popup-volunteer-button");

            NoEorgCloseButton.Disabled = true;

            UpdateCloseButtonText();
        }

        private void InitializeEvents()
        {
            NoEorgCloseButton.OnPressed += OnClosePressed;
            DiscordButton.OnPressed += OnDiscordPressed;
        }

        private void OnClosePressed(BaseButton.ButtonEventArgs args)
        {
            Close();
        }

        private void OnDiscordPressed(BaseButton.ButtonEventArgs args)
        {
            var link = _cfg.GetCVar(FishCVars.EorgPopupLink);
            if (!string.IsNullOrWhiteSpace(link))
            {
                _uri.OpenUri(link);
            }
        }

        private void UpdateCloseButtonText()
        {
            var isWaiting = _remainingTime > 0f;
            NoEorgCloseButton.Text = isWaiting
                ? Loc.GetString("no-eorg-popup-close-button-wait", ("time", (int)MathF.Ceiling(_remainingTime)))
                : Loc.GetString("no-eorg-popup-close-button");
            NoEorgCloseButton.Disabled = isWaiting;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!NoEorgCloseButton.Disabled)
                return;

            _remainingTime = MathF.Max(0f, _remainingTime - args.DeltaSeconds);
            UpdateCloseButtonText();
        }
    }
}
