using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Utility;

namespace Content.Client._Fish.UserInterface.Crt;

[GenerateTypedNameReferences]
public sealed partial class FishCrtActionButton : ContainerButton, IFishCrtThemedControl
{
    public static readonly ResPath DefaultIconRsiPath = new("/Textures/_Fish/Interface/CRT/crt_icons.rsi");

    private static readonly ISawmill Sawmill = Logger.GetSawmill("fish-crt");

    private readonly IResourceCache _resourceCache;
    private readonly StyleBoxFlat _transparentStyle = new() { BackgroundColor = Color.Transparent };
    private FishCrtContentAlignment _contentAlignment = FishCrtContentAlignment.Center;
    private Thickness _contentMargin = new(9, 5);
    private int _contentSeparation = 7;
    private float _iconSize = 18;
    private string? _iconState;
    private ResPath _iconRsiPath = DefaultIconRsiPath;
    private string? _text;
    private FishCrtThemeContext _context = new(
        FishCrtPalettes.Get(FishCrtPalettePreset.Blue),
        new FishCrtAppearanceSettings(true, true));
    private bool _selected;
    private int _textFontSize;
    private FishCrtTone _tone = FishCrtTone.Default;
    private FishCrtButtonVariant _variant = FishCrtButtonVariant.Outline;

    public string? Text
    {
        get => _text;
        set
        {
            if (_text == value)
                return;

            _text = value;
            UpdateText();
        }
    }

    public string? IconState
    {
        get => _iconState;
        set
        {
            _iconState = value;
            UpdateIcon();
        }
    }

    public ResPath IconRsiPath
    {
        get => _iconRsiPath;
        set
        {
            _iconRsiPath = value;
            UpdateIcon();
        }
    }

    public Texture? IconTexture
    {
        get => IconControl.Texture;
        set => IconControl.Texture = value;
    }

    public FishCrtButtonVariant Variant
    {
        get => _variant;
        set
        {
            _variant = value;
            UpdateAppearance();
        }
    }

    public FishCrtTone Tone
    {
        get => _tone;
        set
        {
            _tone = value;
            UpdateAppearance();
        }
    }

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
            UpdateAppearance();
        }
    }

    public FishCrtContentAlignment ContentAlignment
    {
        get => _contentAlignment;
        set
        {
            _contentAlignment = value;
            UpdateAlignment();
        }
    }

    public Thickness ContentMargin
    {
        get => _contentMargin;
        set
        {
            _contentMargin = value;
            UpdateMetrics();
        }
    }

    public int ContentSeparation
    {
        get => _contentSeparation;
        set
        {
            _contentSeparation = value;
            UpdateMetrics();
        }
    }

    public float IconSize
    {
        get => _iconSize;
        set
        {
            _iconSize = value;
            UpdateMetrics();
        }
    }

    /// <summary>
    /// Overrides only this button's text size. Zero keeps the active theme's default font.
    /// </summary>
    public int TextFontSize
    {
        get => _textFontSize;
        set
        {
            _textFontSize = value;
            UpdateAppearance();
        }
    }

    public FishCrtActionButton()
    {
        _resourceCache = IoCManager.Resolve<IResourceCache>();
        RobustXamlLoader.Load(this);
        StyleBoxOverride = _transparentStyle;
        UpdateMetrics();
        UpdateAlignment();
        UpdateAppearance();
    }

    void IFishCrtThemedControl.ApplyCrtTheme(FishCrtThemeContext context)
    {
        ApplyAppearance(context);
    }

    internal void ApplyAppearance(FishCrtThemeContext context)
    {
        _context = context;
        Background.ApplyAppearance(context);
        UpdateAppearance();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        ApplyAppearance(FishCrtThemeHelpers.FindContext(this));
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        if (NameScope != null)
            UpdateAppearance();
    }

    private void UpdateIcon()
    {
        if (NameScope == null)
            return;

        if (string.IsNullOrWhiteSpace(IconState))
        {
            IconControl.Texture = null;
            return;
        }

        try
        {
            var rsi = _resourceCache.GetResource<RSIResource>(IconRsiPath).RSI;
            if (rsi.TryGetState(new RSI.StateId(IconState), out var state))
            {
                IconControl.Texture = state.Frame0;
                return;
            }

            IconControl.Texture = null;
            Sawmill.Warning($"CRT icon state '{IconState}' does not exist in '{IconRsiPath}'.");
        }
        catch (Exception exception)
        {
            IconControl.Texture = null;
            Sawmill.Error($"Failed to load CRT icon state '{IconState}' from '{IconRsiPath}': {exception}");
        }
    }

    private void UpdateAlignment()
    {
        if (NameScope == null)
            return;

        Layout.Align = ContentAlignment switch
        {
            FishCrtContentAlignment.Left => BoxContainer.AlignMode.Begin,
            FishCrtContentAlignment.Right => BoxContainer.AlignMode.End,
            _ => BoxContainer.AlignMode.Center,
        };
        Layout.HorizontalAlignment = HAlignment.Stretch;
    }

    private void UpdateMetrics()
    {
        if (NameScope == null)
            return;

        Layout.Margin = ContentMargin;
        Layout.SeparationOverride = ContentSeparation;
        Layout.InvalidateMeasure();
        IconControl.SetWidth = IconSize;
        IconControl.SetHeight = IconSize;
    }

    private void UpdateAppearance()
    {
        if (NameScope == null)
            return;

        UpdateText();

        if (!_context.ThemeEnabled)
        {
            UpdateNanoAppearance();
            return;
        }

        RemoveStyleClass(ContainerButton.StyleClassButton);
        RemoveStyleClass(StyleNano.ButtonCaution);
        ModulateSelfOverride = null;
        StyleBoxOverride = _transparentStyle;
        var palette = _context.Palette;
        var isDanger = Tone == FishCrtTone.Danger || Variant == FishCrtButtonVariant.Danger;
        Color background;
        Color border;
        Color foreground;

        if (DrawMode == DrawModeEnum.Disabled)
        {
            background = palette.DisabledBackground;
            border = palette.Muted;
            foreground = palette.DisabledForeground;
        }
        else if (isDanger)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => Color.InterpolateBetween(palette.Background, palette.Danger, 0.65f),
                DrawModeEnum.Hover => Color.InterpolateBetween(palette.Danger, Color.White, 0.18f),
                _ => palette.Danger,
            };
            border = palette.Danger;
            foreground = palette.Background;
        }
        else if (Selected || Variant == FishCrtButtonVariant.Filled)
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => palette.PressedBackground,
                DrawModeEnum.Hover => Color.InterpolateBetween(palette.Fill, Color.White, 0.2f),
                _ => palette.Fill,
            };
            border = palette.Border;
            foreground = palette.FillForeground;
        }
        else
        {
            background = DrawMode switch
            {
                DrawModeEnum.Pressed => palette.PressedBackground.WithAlpha(0.75f),
                DrawModeEnum.Hover => palette.HoverBackground,
                _ => palette.Background.WithAlpha(0.72f),
            };
            border = palette.Border;
            foreground = Tone switch
            {
                FishCrtTone.Good => palette.Good,
                FishCrtTone.Muted => palette.Muted,
                FishCrtTone.Warning => palette.Warning,
                _ => palette.Foreground,
            };
        }

        Background.SetColorOverrides(background, border);
        IconControl.ModulateSelfOverride = foreground;
        TextLabel.ModulateSelfOverride = foreground;
    }

    private void UpdateNanoAppearance()
    {
        AddStyleClass(ContainerButton.StyleClassButton);
        StyleBoxOverride = null;
        var isDanger = Tone == FishCrtTone.Danger || Variant == FishCrtButtonVariant.Danger;
        if (isDanger)
            AddStyleClass(StyleNano.ButtonCaution);
        else
            RemoveStyleClass(StyleNano.ButtonCaution);

        ModulateSelfOverride = !isDanger &&
                               (Selected || Variant == FishCrtButtonVariant.Filled) &&
                               DrawMode != DrawModeEnum.Disabled
            ? DrawMode == DrawModeEnum.Hover
                ? StyleNano.ButtonColorGoodHovered
                : StyleNano.ButtonColorPressed
            : null;

        var foreground = Tone switch
        {
            FishCrtTone.Good => StyleNano.GoodGreenFore,
            FishCrtTone.Muted => StyleNano.DisabledFore,
            FishCrtTone.Warning => StyleNano.ConcerningOrangeFore,
            _ => (Color?) null,
        };

        IconControl.ModulateSelfOverride = foreground;
        TextLabel.ModulateSelfOverride = foreground;
    }

    private void UpdateText()
    {
        if (NameScope == null)
            return;

        TextLabel.SetMessage(FishCrtThemeHelpers.CreateTextMessage(
            _text,
            _context,
            TextFontSize));
    }
}
