using Content.Shared._Fish.PerformanceGuardian;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.IoC;

namespace Content.Client._Fish.PerformanceGuardian;

[GenerateTypedNameReferences]
public sealed partial class PerformanceGuardianWindow : DefaultWindow
{
    [Dependency] private readonly IConsoleHost _console = default!;

    public event Action? RefreshPressed;
    public event Action? DiagnosePressed;

    public PerformanceGuardianWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Title = Loc.GetString("pg-window-title");
        RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();
        DiagnoseButton.OnPressed += _ => DiagnosePressed?.Invoke();
    }

    public void Apply(PgReport report)
    {
        StatusLabel.Text = Loc.GetString("pg-status-line",
            ("state", report.ServerState),
            ("mode", ModeRu(report.Mode)));

        ContentRoot.DisposeAllChildren();

        AddHeader(Loc.GetString("pg-section-server"));
        AddLine(Loc.GetString("pg-line-state", ("value", report.ServerState)));
        AddLine(Loc.GetString("pg-line-tps", ("tps", report.Tps.ToString("F1")), ("ms", report.TickMs.ToString("F1")), ("budget", report.TickBudgetMs.ToString("F1"))));
        AddLine(Loc.GetString("pg-line-counts",
            ("entities", report.EntityCount),
            ("grids", report.GridCount),
            ("players", report.PlayerCount)));
        AddLine(Loc.GetString("pg-line-physics", ("awake", report.AwakeBodies)));
        AddLine(Loc.GetString("pg-line-atmos", ("tiles", report.AtmosActiveTiles), ("hot", report.AtmosHotspots)));
        AddLine(Loc.GetString("pg-line-events", ("rate", report.EventRatePerSec)));

        AddHeader(Loc.GetString("pg-section-source"));
        AddLine(report.PrimarySourceText);

        AddHeader(Loc.GetString("pg-section-place"));
        AddTeleportRow(report.PlaceName, report.PlaceTeleportTarget);

        AddHeader(Loc.GetString("pg-section-coords"));
        AddTeleportRow(report.CoordinatesText, report.PlaceTeleportTarget);

        AddHeader(Loc.GetString("pg-section-top-entities"));
        if (report.TopEntities.Count == 0)
            AddLine(Loc.GetString("pg-empty-list"));
        else
        {
            foreach (var row in report.TopEntities)
                AddTeleportRow($"• {row.Name} — {row.Detail}", row.TeleportTarget);
        }

        AddHeader(Loc.GetString("pg-section-nearby"));
        if (report.NearbyPlayers.Count == 0)
            AddLine(Loc.GetString("pg-empty-list"));
        else
        {
            foreach (var row in report.NearbyPlayers)
                AddTeleportRow($"• {row.Name} — {row.Detail}", row.TeleportTarget);
        }

        AddHeader(Loc.GetString("pg-section-incident"));
        if (report.LastIncidentAt == null || string.IsNullOrEmpty(report.LastIncidentSummary))
            AddLine(Loc.GetString("pg-no-incident"));
        else
            AddLine($"{report.LastIncidentSummary} ({report.LastIncidentAt.Value:hh\\:mm\\:ss})");

        AddHeader(Loc.GetString("pg-section-advice"));
        AddLine(string.IsNullOrEmpty(report.Recommendation)
            ? Loc.GetString("pg-no-advice")
            : report.Recommendation);
    }

    private void AddHeader(string text)
    {
        ContentRoot.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelHeading" },
        });
    }

    private void AddLine(string text)
    {
        ContentRoot.AddChild(new Label
        {
            Text = text,
            HorizontalExpand = true,
        });
    }

    private void AddTeleportRow(string text, NetEntity? target)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };

        row.AddChild(new Label
        {
            Text = text,
            HorizontalExpand = true,
        });

        if (target is { Valid: true } nent)
        {
            var btn = new Button
            {
                Text = Loc.GetString("pg-btn-teleport"),
                MinWidth = 90,
            };
            var captured = nent;
            btn.OnPressed += _ => _console.ExecuteCommand($"tpto {captured}");
            row.AddChild(btn);
        }

        ContentRoot.AddChild(row);
    }

    private static string ModeRu(PgMode mode) => mode switch
    {
        PgMode.Incident => Loc.GetString("pg-mode-incident"),
        _ => Loc.GetString("pg-mode-idle"),
    };
}
