using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Fish.PerformanceGuardian;

/// <summary>
/// Тонкая F7-вкладка: открывает простое окно Performance Guardian.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PerformanceGuardianLauncherTab : BoxContainer
{
    public PerformanceGuardianLauncherTab()
    {
        RobustXamlLoader.Load(this);
        OpenButton.OnPressed += _ =>
        {
            var controller = UserInterfaceManager.GetUIController<PerformanceGuardianUIController>();
            controller.OpenWindow();
        };
    }
}
