- type: jobIcon
  parent: IconCoreBase
  id: IconWithUnknow
  jobName: Кто-то
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: null #WithUnknow

#Icon


- type: jobIcon
  parent: JobIcon
  id: IconGhostWM
  icon:
    sprite: /Textures/_Fish/PlanetWar/WM/Icon.rsi
    state: ArmPE1
  jobName: Призрак


#Id
